#  WhatsApp  API
whatsapp.verify.token=patient-tracker
# or whatever you're using for webhook verification
whatsapp.api.url=https://graph.facebook.com/v22.0/688966954309422/messages
whatsapp.phone.number.id=688966954309422
whatsapp.token=EAARsK9Fz4qYBP44DFuxWxyrriic10yWiwVZB1ILcmUszc4kBD1Y9mm5T98o8gY8oeoDKCGLTsJUoVekXOPB0ZC6AH39My3tjsAdfPTtQFtdVhknsCzTQ0sZBXMMZB4ubu9q05QhvMKmOZCZCcUDwyvDKAbbhbYTPMDiNZCDF1xyuHOo6NuKguRD0E0ISWQki9OLF8lIYOGT1XasfFXQG2bSF8Y3aAM5m9VHlNQn2WBn3S49dSHTqWEErZB1OsWYXS5EZD
openai.api.key=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
#google Map Api key:
google.places.api.key=AIzaSyBLYW8_ntIjhS7GK1HQcoelHNn3ZK1UmZo
