#  WhatsApp  API
whatsapp.verify.token=hope123secure
  # or whatever you're using for webhook verification
whatsapp.api.url=https://graph.facebook.com/v18.0/751231778063265/messages
whatsapp.phone.number.id=751231778063265
whatsapp.token=EAAZAhYWLSZBRsBPPW0WVUyYXeNG3xCQlhTJZAdJX5hSF2TbVjnkrYcVNZA8u7qH9xxi59dpC3tUkwTerLVE73630inIW6X6eco90oAZCTI4FczgfZBdG9DnVb83eBZCQaue9f56uEYWorlfFYZBDTjZBZCRvHRkbRRULn5A6jQqFZChXZCuewoKaZBlWLIzGx6fFxzJsl3tLMPey0yZC8YYsEXtcH5H4zYjbv0iCePhzer2NyxnLEkoQZDZD
#  Firebase Admin SDK
firebase.credentials.path=classpath:firebase-service-account.json
