#  WhatsApp  API
whatsapp.verify.token=patient-tracker
# or whatever you're using for webhook verification
whatsapp.api.url=https://graph.facebook.com/v22.0/688966954309422/messages
whatsapp.phone.number.id=688966954309422
whatsapp.token=EAARsK9Fz4qYBQHRZBFZCz2HERrXoyCgkbZCycTeGTHa4bJ9KP0xJ2dkQgriUmZAut5da38WqUQLjFS9B357Oub8Hp19jPRZBTkXxTMxNVYv2dEFJ4ZAelIZATZBg5HEZBgOmCZCEqfkdTvfg3jc31ZCokzMUuMtMvAOhMUayv4rFIG5tZCp3ZASsVVP2oXnwlqh7LUsW1x4ClinpAtOJh2uQjMQGevuqnHRFZBTLI4mKOowyC9R99pNUHeTy6uBWkD1VxRDkZAjhM5GDDqgL5MddxTjZClWrYZCV5jtBqB8fsnPdqUggZD
openai.api.key=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
#google Map Api key:
google.places.api.key=AIzaSyBLYW8_ntIjhS7GK1HQcoelHNn3ZK1UmZo
