# application.properties or application.yml
whatsapp.api.url=https://graph.facebook.com/v18.0/651051104766013/messages
firebase.config.path=classpath:firebase-service-account.json
whatsapp.token=EAAKgIBYDjgoBO4WOmrLqgoelEj9I8VpXsjl8sW5BjxF2G3lbSqjogZCUj3J6lfxJPGfRgljOeTyg8eLVVBZBOfxANL07406AVL8TGQq5FoPltHPv8Ti0MXIn84KRb1BN0kxd9sksPTbsyYrTbnfHtbTfbAmqBpz7Rz8iE5S4WIpViQLHARp4cbhwK2JOZAhleHh37gmqCeUtuMnpfDAB4MeRNA7BYhsLMIZD
