#  WhatsApp  API
whatsapp.verify.token=hope123secure
  # or whatever you're using for webhook verification
whatsapp.api.url=https://graph.facebook.com/v18.0/751231778063265/messages
whatsapp.phone.number.id=751231778063265
whatsapp.token=EAAZAhYWLSZBRsBPAypsPg2m99Mlw3pilT7PE4cNzAWRNRgDtxi56gNzVQxAOkZBl1YrBdLlHyij9QomcFjONYZAj4xmsPCZCUuCvaDFk3eb1Ti2TEYfhxYprsdeZCehpBFfwAwQSpwOEN5Mhp5ZCZB2HAVBzKyZC6TWtQmLZAPX3Wq760eMxE3ixORRVYFyndRqZANFsOSV6NebpyGVHicvrUpCOKOqR5UOO3EAi4pZAZBlnTl1QFUwZDZD
#  Firebase Admin SDK
firebase.credentials.path=classpath:firebase-service-account.json
#OpenAi API key:
openai.api.key="paste your token here"