#  WhatsApp  API
whatsapp.verify.token=patient-tracker
# or whatever you're using for webhook verification
whatsapp.api.url=https://graph.facebook.com/v22.0/688966954309422/messages
whatsapp.phone.number.id=688966954309422
whatsapp.token=EAARsK9Fz4qYBP39It60FqhNqv2hjpLZBBEtO8ZAmsZBnGxQcrxhHCsvtKOvaEKpquSmtEhUBhyheZB0ZCmJ4maBjZAZArmoxqnvZAuwwP2uAnbVngHCWHcehreevmFH4n3v1LPLIm3oWIdDblLXPQPriZBfP9w8EKl7QX7m0ZCjx4TmsK5Dw0qhtfEek0wOQ8nX4aFwzaxaH2WIHcbyExxjm9iAR34xVnFbytOjIoqApJGATG803mZBmXEwd0fAcfZAH2zii9rTpvSoTv6o43jALySl2LToS0rctvAvzH57aZCYUZD
openai.api.key=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
#google Map Api key:
google.places.api.key=AIzaSyBLYW8_ntIjhS7GK1HQcoelHNn3ZK1UmZo
